:url: http://www.buch.de
:url_advanced: http://www.buch.de/shop/home/suche/;jsessionid=9D7F7A7534E52C6534E16D0591D829F9.tc6p?timestamp=1363637153843&sswg=ANY
:search_form: quicksearch
:search_field: sq
:link_class: pm_titelDetailsAction
:book:
  :name: .detailsTitle .pm_titel
  :ean: .primaerfeatures .ean .value
  :author: .b9_author
  :description: ! '#pm_kurzbeschreibung .redaktion'
  :price: .b9sellbox .b9Price .pm_preis
